typography_spectrum: 0.09156244224868715
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18375582969747484
  lightness: 0.622361941030249
  saturation: 0.43969827238470316
  rhythmicContrast: 0.7616613933350891
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8630321826785803
analytics:
  google: null
  facebook: null
  twitter: null
name: merriman
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Merriman Marketing
description: Let's make you look good
purpose: []
